% LLC Converter default input parameters 

% Copyright 2025-2026 The MathWorks, Inc.
modelName = "LLCResonantConverterFullBridge";
LLCSpec.minInputVoltage =  simscape.Value(350,"V"); % V, minimum input voltage
LLCSpec.maxInputVoltage =  simscape.Value(400,"V"); % V, maximum input voltage
LLCSpec.minOutputVoltage = simscape.Value(300,"V"); % V, minimum output voltage
LLCSpec.maxOutputVoltage = simscape.Value(400,"V"); % V, maximum output voltage
LLCSpec.ratedOutputPower = simscape.Value(10000,"W"); % W, rated power 
LLCSpec.resonantFrequency = simscape.Value(100e3,"Hz"); % Hz, resonant frequency
LLCSpec.mosfetDrainSourceCapacitance = simscape.Value(200e-12,"F"); % F, parasitic capacitance of the MOSFET
LLCSpec.inductanceDistributionFactor = 0.95; % Inductance distribution factor (h)
LLCSpec.Rco = 0.02; % Output filter capacitor ESR resistance (Ohm)
LLCSpec.R1 = 1e-4; % Transformer primary resistance (Ohm)
LLCSpec.R2 = 1e-4; % Transformer secondary resistance (Ohm)
LLCSpec.Rcr = 1e-4; % Resonant capacitor resistance (Ohm)
LLCSpec.qualityFactor = 0.6; % Quality factor
LLCSpec.k = 5; % (Lm+Lr)/Lr ratio
[designTable, LLCDesign]  = designLLCFullBridgeConverter(LLCSpec,DisplayTableFlag=false);
nominalOutputVoltage = (LLCSpec.minOutputVoltage.value+LLCSpec.maxOutputVoltage.value)/2;
LLCController.Kp = 3.5; % Proportional controller parameter
LLCController.Ki = 5; % Integral controller parameter
LLCController.Kd = 0; % Differential controller parameter
LLCController.Ts = 1e-6; % Sample time (s)
frequencyRange.minFreq = 60e3;
frequencyRange.maxFreq = 155e3;
LLCSpec.Co = 0.0008; % Filter capacitance
LLCDesign.Rco = 0.02; % Ouput filter capacitor resistance (Ohm)
LLCDesign.R1 = 1e-4; % Transformer primary resistance (Ohm)
LLCDesign.R2 = 1e-4; % Transformer secondary resistance (Ohm)
LLCDesign.Rcr = 1e-4; % Resonant capacitor resistance (Ohm)
llcCompensator.numSDomain = [1 1.4630e+03 1.7947e+06];
llcCompensator.denSDomain = [1 2.7486e+03 0];
llcCompensator.numZDomain = [1.0000 -1.9985 0.9985];
llcCompensator.denZDomain = [1 -1.9973 0.9973];
llcCompensator.wn = 1.1223e+03;
llcCompensator.Ki = 1;
llcCompensator.constantVCOGain = 1;
llcCompensator.resonantFrequency = LLCSpec.resonantFrequency.value;
llcCompensator.minPUfrequency = 0.6;
llcCompensator.maxPUfrequency = 1.55;
llcCompensator.deadTime = 2.5e-7;
LLCController.vcoGainVec = [1,1.2]; % Voltage controlled oscillator gain vector (Volt/perunit frequency)
freqOffsetPU = 0; % pu
Rload = 10; % Ohm
switchingFrequency = 100e3; % Hz, Linearization switching frequency
inputVoltage = 380; % V, input DC voltage
primaryMOSFETBlock =  "MOSFET (Ideal, Switching) without Thermal";
secondaryDiodeBlock = "Ideal Diode";
Rload_Ohm = simscape.Value(20.6, "Ohm");     % Output load resistance
inputVoltage_V = simscape.Value(380, "V");   % Input DC voltage
